name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    -  name: login to AWS ECR
       run: echo "Logging in to Amazon ECR... ${{ secrets.AWS_REGION}}" 

      #  run: 
      #   aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
